### ISSUE TITLE
Ui.png not as expected

### ISSUE THREAD

**Issue by damithc** [deepimpactmir/ip#3]
@deepimpactmir Your Ui.png is a screenshot of code. It should show the UI of the application instead. 
See https://nus-cs2103-ay2223s1.github.io/website/admin/ip-showcase.html for examples.

**Comment by deepimpactmir** [comment]
Thanks for the catch! I pushed the correct png in the latest commit, seems like I mixed it up with one of the screenshots for the tutorial.
